import Hero from "@/components/Hero";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="overfolw-hidden ">
      <Head>
        <title>ASR Mizar Consulting </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/Logo.svg' />
      </Head>
      <main>
        <Hero />

        <div className='px-10 bg-blue-1 lg:pb-20 md:px-40 xl:px-80 pt-14 flex flex-col lg:flex-row '>
          <div className="lg:max-w-2xl  lg:p-10" >
          <h2 className='text-blue-900  text-xl font-black lg:text-2xl  max-w-[250px] lg:max-w-2xl '>
            Despre ASR Mizar Consulting -
          </h2>
          <h3 className='text-gray-400  text-md font-bold mt-5    max-w-[250px]'>
            Expertiza si calitate in construirea proiectelor tale
          </h3>

          <p  className="mt-5 text-gray-800 font-medium  max-h-60 lg:max-h-full lg:overflow-hidden  overflow-scroll scrollbar-hide"> 
            ASR Mizar Consulting este o firma cu o solida reputatie in domeniul
            constructiilor, cu peste 6 ani de experienta in oferirea de servicii
            premium clientilor nostri. Ne mandrim cu un portofoliu impresionant
            de proiecte realizate cu succes si clienti multumiti de calitatea si
            atentia acordate fiecarei lucrari. <br/><br/>
            Ne angajam sa fim partenerul
            dumneavoastra de incredere in crearea si realizarea proiectelor
            dumneavoastra, asistandu-va in fiecare etapa a procesului, de la
            intocmirea documentatiei si bugetelor, pana la executia lucrarii.
          </p>
          </div>
          <div  className="mt-10 lg:mt-0   flex lg:space-x-8  ">
              <div className="rounded-full relative w-full  h-80 lg:hidden">
              <Image src="/img-1.webp" className="absolute border-4 border-orange-400 object-contain" width={250} height={250} />
              <Image src="/img-2.webp" className="absolute border-4 border-blue-900 object-contain bottom-0 right-0 " width={250} height={250} />
              <Image src="/img-3.webp" className="absolute border-4 border-orange-400 object-contain -bottom-2 left-0 " width={150} height={250} />
              </div>

              <div className="w-64  h-full relative hidden lg:flex overflow-hidden " >
              <Image src="/img-1.webp" className=" border-4 border-orange-400 object-cover ease-in-out duration-300  hover:scale-125" fill />
              </div>
              <div className="w-64 h-full relative hidden lg:flex overflow-hidden" >
              <Image src="/img-2.webp" className=" border-4 border-orange-400 object-cover ease-in-out duration-300  hover:scale-125" fill />
              </div>
          </div>
            
        </div>
      </main>
    </div>
  );
}
